services:
  - type: web
    name: titanic-survival-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
